name: Native build

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  # Customize the Meson build type here (plain, debug, debugoptimized, release, minsize, custom)
  BUILD_TYPE: release
  ENABLE_LTO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: meson valac libudev-dev libevdev-dev zlib1g-dev libgee-0.8-dev
        version: 1.0

    - name: Setup build directory
      run: meson setup ${{github.workspace}}/build --fatal-meson-warnings --buildtype=${{env.BUILD_TYPE}} -Db_lto=${{env.ENABLE_LTO}}

    - name: Build
      run: meson compile -C ${{github.workspace}}/build
